/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedWalletsIndexRouteImport } from './routes/_authenticated/wallets/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTransactionsIndexRouteImport } from './routes/_authenticated/transactions/index'
import { Route as AuthenticatedStakingIndexRouteImport } from './routes/_authenticated/staking/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSecurityIndexRouteImport } from './routes/_authenticated/security/index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedOrganizationsIndexRouteImport } from './routes/_authenticated/organizations/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedGovernanceIndexRouteImport } from './routes/_authenticated/governance/index'
import { Route as AuthenticatedBlockchainIndexRouteImport } from './routes/_authenticated/blockchain/index'
import { Route as AuthenticatedAuditLogsIndexRouteImport } from './routes/_authenticated/audit-logs/index'
import { Route as AuthenticatedAnalyticsIndexRouteImport } from './routes/_authenticated/analytics/index'
import { Route as AuthenticatedWalletsAnalyticsRouteImport } from './routes/_authenticated/wallets/analytics'
import { Route as AuthenticatedTransactionsBatchesRouteImport } from './routes/_authenticated/transactions/batches'
import { Route as AuthenticatedTransactionsApprovalsRouteImport } from './routes/_authenticated/transactions/approvals'
import { Route as AuthenticatedStakingPositionsRouteImport } from './routes/_authenticated/staking/positions'
import { Route as AuthenticatedStakingPoolsRouteImport } from './routes/_authenticated/staking/pools'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedSecuritySessionsRouteImport } from './routes/_authenticated/security/sessions'
import { Route as AuthenticatedSecurityPoliciesRouteImport } from './routes/_authenticated/security/policies'
import { Route as AuthenticatedSecurityMpcKeysRouteImport } from './routes/_authenticated/security/mpc-keys'
import { Route as AuthenticatedGovernanceProposalsRouteImport } from './routes/_authenticated/governance/proposals'
import { Route as AuthenticatedGovernanceDelegationsRouteImport } from './routes/_authenticated/governance/delegations'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedBlockchainWithdrawalsRouteImport } from './routes/_authenticated/blockchain/withdrawals'
import { Route as AuthenticatedBlockchainDepositsRouteImport } from './routes/_authenticated/blockchain/deposits'
import { Route as AuthenticatedAnalyticsUsersRouteImport } from './routes/_authenticated/analytics/users'
import { Route as AuthenticatedAnalyticsRiskRouteImport } from './routes/_authenticated/analytics/risk'
import { Route as AuthenticatedAnalyticsRealTimeRouteImport } from './routes/_authenticated/analytics/real-time'
import { Route as AuthenticatedAnalyticsPerformanceRouteImport } from './routes/_authenticated/analytics/performance'
import { Route as AuthenticatedAnalyticsFinancialRouteImport } from './routes/_authenticated/analytics/financial'
import { Route as AuthenticatedGovernanceProposalsIdRouteImport } from './routes/_authenticated/governance/proposals.$id'
import { Route as AuthenticatedGovernanceDelegationsIdRouteImport } from './routes/_authenticated/governance/delegations.$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWalletsIndexRoute =
  AuthenticatedWalletsIndexRouteImport.update({
    id: '/wallets/',
    path: '/wallets/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransactionsIndexRoute =
  AuthenticatedTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStakingIndexRoute =
  AuthenticatedStakingIndexRouteImport.update({
    id: '/staking/',
    path: '/staking/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSecurityIndexRoute =
  AuthenticatedSecurityIndexRouteImport.update({
    id: '/security/',
    path: '/security/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrganizationsIndexRoute =
  AuthenticatedOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGovernanceIndexRoute =
  AuthenticatedGovernanceIndexRouteImport.update({
    id: '/governance/',
    path: '/governance/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBlockchainIndexRoute =
  AuthenticatedBlockchainIndexRouteImport.update({
    id: '/blockchain/',
    path: '/blockchain/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditLogsIndexRoute =
  AuthenticatedAuditLogsIndexRouteImport.update({
    id: '/audit-logs/',
    path: '/audit-logs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsIndexRoute =
  AuthenticatedAnalyticsIndexRouteImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWalletsAnalyticsRoute =
  AuthenticatedWalletsAnalyticsRouteImport.update({
    id: '/wallets/analytics',
    path: '/wallets/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTransactionsBatchesRoute =
  AuthenticatedTransactionsBatchesRouteImport.update({
    id: '/transactions/batches',
    path: '/transactions/batches',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTransactionsApprovalsRoute =
  AuthenticatedTransactionsApprovalsRouteImport.update({
    id: '/transactions/approvals',
    path: '/transactions/approvals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStakingPositionsRoute =
  AuthenticatedStakingPositionsRouteImport.update({
    id: '/staking/positions',
    path: '/staking/positions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStakingPoolsRoute =
  AuthenticatedStakingPoolsRouteImport.update({
    id: '/staking/pools',
    path: '/staking/pools',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSecuritySessionsRoute =
  AuthenticatedSecuritySessionsRouteImport.update({
    id: '/security/sessions',
    path: '/security/sessions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSecurityPoliciesRoute =
  AuthenticatedSecurityPoliciesRouteImport.update({
    id: '/security/policies',
    path: '/security/policies',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSecurityMpcKeysRoute =
  AuthenticatedSecurityMpcKeysRouteImport.update({
    id: '/security/mpc-keys',
    path: '/security/mpc-keys',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGovernanceProposalsRoute =
  AuthenticatedGovernanceProposalsRouteImport.update({
    id: '/governance/proposals',
    path: '/governance/proposals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGovernanceDelegationsRoute =
  AuthenticatedGovernanceDelegationsRouteImport.update({
    id: '/governance/delegations',
    path: '/governance/delegations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBlockchainWithdrawalsRoute =
  AuthenticatedBlockchainWithdrawalsRouteImport.update({
    id: '/blockchain/withdrawals',
    path: '/blockchain/withdrawals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBlockchainDepositsRoute =
  AuthenticatedBlockchainDepositsRouteImport.update({
    id: '/blockchain/deposits',
    path: '/blockchain/deposits',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsUsersRoute =
  AuthenticatedAnalyticsUsersRouteImport.update({
    id: '/analytics/users',
    path: '/analytics/users',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsRiskRoute =
  AuthenticatedAnalyticsRiskRouteImport.update({
    id: '/analytics/risk',
    path: '/analytics/risk',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsRealTimeRoute =
  AuthenticatedAnalyticsRealTimeRouteImport.update({
    id: '/analytics/real-time',
    path: '/analytics/real-time',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsPerformanceRoute =
  AuthenticatedAnalyticsPerformanceRouteImport.update({
    id: '/analytics/performance',
    path: '/analytics/performance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsFinancialRoute =
  AuthenticatedAnalyticsFinancialRouteImport.update({
    id: '/analytics/financial',
    path: '/analytics/financial',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGovernanceProposalsIdRoute =
  AuthenticatedGovernanceProposalsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedGovernanceProposalsRoute,
  } as any)
const AuthenticatedGovernanceDelegationsIdRoute =
  AuthenticatedGovernanceDelegationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedGovernanceDelegationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/analytics/financial': typeof AuthenticatedAnalyticsFinancialRoute
  '/analytics/performance': typeof AuthenticatedAnalyticsPerformanceRoute
  '/analytics/real-time': typeof AuthenticatedAnalyticsRealTimeRoute
  '/analytics/risk': typeof AuthenticatedAnalyticsRiskRoute
  '/analytics/users': typeof AuthenticatedAnalyticsUsersRoute
  '/blockchain/deposits': typeof AuthenticatedBlockchainDepositsRoute
  '/blockchain/withdrawals': typeof AuthenticatedBlockchainWithdrawalsRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/governance/delegations': typeof AuthenticatedGovernanceDelegationsRouteWithChildren
  '/governance/proposals': typeof AuthenticatedGovernanceProposalsRouteWithChildren
  '/security/mpc-keys': typeof AuthenticatedSecurityMpcKeysRoute
  '/security/policies': typeof AuthenticatedSecurityPoliciesRoute
  '/security/sessions': typeof AuthenticatedSecuritySessionsRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/staking/pools': typeof AuthenticatedStakingPoolsRoute
  '/staking/positions': typeof AuthenticatedStakingPositionsRoute
  '/transactions/approvals': typeof AuthenticatedTransactionsApprovalsRoute
  '/transactions/batches': typeof AuthenticatedTransactionsBatchesRoute
  '/wallets/analytics': typeof AuthenticatedWalletsAnalyticsRoute
  '/analytics': typeof AuthenticatedAnalyticsIndexRoute
  '/audit-logs': typeof AuthenticatedAuditLogsIndexRoute
  '/blockchain': typeof AuthenticatedBlockchainIndexRoute
  '/governance': typeof AuthenticatedGovernanceIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/organizations': typeof AuthenticatedOrganizationsIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/security': typeof AuthenticatedSecurityIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/staking': typeof AuthenticatedStakingIndexRoute
  '/transactions': typeof AuthenticatedTransactionsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/wallets': typeof AuthenticatedWalletsIndexRoute
  '/governance/delegations/$id': typeof AuthenticatedGovernanceDelegationsIdRoute
  '/governance/proposals/$id': typeof AuthenticatedGovernanceProposalsIdRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/analytics/financial': typeof AuthenticatedAnalyticsFinancialRoute
  '/analytics/performance': typeof AuthenticatedAnalyticsPerformanceRoute
  '/analytics/real-time': typeof AuthenticatedAnalyticsRealTimeRoute
  '/analytics/risk': typeof AuthenticatedAnalyticsRiskRoute
  '/analytics/users': typeof AuthenticatedAnalyticsUsersRoute
  '/blockchain/deposits': typeof AuthenticatedBlockchainDepositsRoute
  '/blockchain/withdrawals': typeof AuthenticatedBlockchainWithdrawalsRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/governance/delegations': typeof AuthenticatedGovernanceDelegationsRouteWithChildren
  '/governance/proposals': typeof AuthenticatedGovernanceProposalsRouteWithChildren
  '/security/mpc-keys': typeof AuthenticatedSecurityMpcKeysRoute
  '/security/policies': typeof AuthenticatedSecurityPoliciesRoute
  '/security/sessions': typeof AuthenticatedSecuritySessionsRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/staking/pools': typeof AuthenticatedStakingPoolsRoute
  '/staking/positions': typeof AuthenticatedStakingPositionsRoute
  '/transactions/approvals': typeof AuthenticatedTransactionsApprovalsRoute
  '/transactions/batches': typeof AuthenticatedTransactionsBatchesRoute
  '/wallets/analytics': typeof AuthenticatedWalletsAnalyticsRoute
  '/analytics': typeof AuthenticatedAnalyticsIndexRoute
  '/audit-logs': typeof AuthenticatedAuditLogsIndexRoute
  '/blockchain': typeof AuthenticatedBlockchainIndexRoute
  '/governance': typeof AuthenticatedGovernanceIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/organizations': typeof AuthenticatedOrganizationsIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/security': typeof AuthenticatedSecurityIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/staking': typeof AuthenticatedStakingIndexRoute
  '/transactions': typeof AuthenticatedTransactionsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/wallets': typeof AuthenticatedWalletsIndexRoute
  '/governance/delegations/$id': typeof AuthenticatedGovernanceDelegationsIdRoute
  '/governance/proposals/$id': typeof AuthenticatedGovernanceProposalsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/analytics/financial': typeof AuthenticatedAnalyticsFinancialRoute
  '/_authenticated/analytics/performance': typeof AuthenticatedAnalyticsPerformanceRoute
  '/_authenticated/analytics/real-time': typeof AuthenticatedAnalyticsRealTimeRoute
  '/_authenticated/analytics/risk': typeof AuthenticatedAnalyticsRiskRoute
  '/_authenticated/analytics/users': typeof AuthenticatedAnalyticsUsersRoute
  '/_authenticated/blockchain/deposits': typeof AuthenticatedBlockchainDepositsRoute
  '/_authenticated/blockchain/withdrawals': typeof AuthenticatedBlockchainWithdrawalsRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/governance/delegations': typeof AuthenticatedGovernanceDelegationsRouteWithChildren
  '/_authenticated/governance/proposals': typeof AuthenticatedGovernanceProposalsRouteWithChildren
  '/_authenticated/security/mpc-keys': typeof AuthenticatedSecurityMpcKeysRoute
  '/_authenticated/security/policies': typeof AuthenticatedSecurityPoliciesRoute
  '/_authenticated/security/sessions': typeof AuthenticatedSecuritySessionsRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/staking/pools': typeof AuthenticatedStakingPoolsRoute
  '/_authenticated/staking/positions': typeof AuthenticatedStakingPositionsRoute
  '/_authenticated/transactions/approvals': typeof AuthenticatedTransactionsApprovalsRoute
  '/_authenticated/transactions/batches': typeof AuthenticatedTransactionsBatchesRoute
  '/_authenticated/wallets/analytics': typeof AuthenticatedWalletsAnalyticsRoute
  '/_authenticated/analytics/': typeof AuthenticatedAnalyticsIndexRoute
  '/_authenticated/audit-logs/': typeof AuthenticatedAuditLogsIndexRoute
  '/_authenticated/blockchain/': typeof AuthenticatedBlockchainIndexRoute
  '/_authenticated/governance/': typeof AuthenticatedGovernanceIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/organizations/': typeof AuthenticatedOrganizationsIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/security/': typeof AuthenticatedSecurityIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/staking/': typeof AuthenticatedStakingIndexRoute
  '/_authenticated/transactions/': typeof AuthenticatedTransactionsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/wallets/': typeof AuthenticatedWalletsIndexRoute
  '/_authenticated/governance/delegations/$id': typeof AuthenticatedGovernanceDelegationsIdRoute
  '/_authenticated/governance/proposals/$id': typeof AuthenticatedGovernanceProposalsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/analytics/financial'
    | '/analytics/performance'
    | '/analytics/real-time'
    | '/analytics/risk'
    | '/analytics/users'
    | '/blockchain/deposits'
    | '/blockchain/withdrawals'
    | '/errors/$error'
    | '/governance/delegations'
    | '/governance/proposals'
    | '/security/mpc-keys'
    | '/security/policies'
    | '/security/sessions'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/staking/pools'
    | '/staking/positions'
    | '/transactions/approvals'
    | '/transactions/batches'
    | '/wallets/analytics'
    | '/analytics'
    | '/audit-logs'
    | '/blockchain'
    | '/governance'
    | '/help-center'
    | '/organizations'
    | '/reports'
    | '/security'
    | '/settings/'
    | '/staking'
    | '/transactions'
    | '/users'
    | '/wallets'
    | '/governance/delegations/$id'
    | '/governance/proposals/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/analytics/financial'
    | '/analytics/performance'
    | '/analytics/real-time'
    | '/analytics/risk'
    | '/analytics/users'
    | '/blockchain/deposits'
    | '/blockchain/withdrawals'
    | '/errors/$error'
    | '/governance/delegations'
    | '/governance/proposals'
    | '/security/mpc-keys'
    | '/security/policies'
    | '/security/sessions'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/staking/pools'
    | '/staking/positions'
    | '/transactions/approvals'
    | '/transactions/batches'
    | '/wallets/analytics'
    | '/analytics'
    | '/audit-logs'
    | '/blockchain'
    | '/governance'
    | '/help-center'
    | '/organizations'
    | '/reports'
    | '/security'
    | '/settings'
    | '/staking'
    | '/transactions'
    | '/users'
    | '/wallets'
    | '/governance/delegations/$id'
    | '/governance/proposals/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/analytics/financial'
    | '/_authenticated/analytics/performance'
    | '/_authenticated/analytics/real-time'
    | '/_authenticated/analytics/risk'
    | '/_authenticated/analytics/users'
    | '/_authenticated/blockchain/deposits'
    | '/_authenticated/blockchain/withdrawals'
    | '/_authenticated/errors/$error'
    | '/_authenticated/governance/delegations'
    | '/_authenticated/governance/proposals'
    | '/_authenticated/security/mpc-keys'
    | '/_authenticated/security/policies'
    | '/_authenticated/security/sessions'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/staking/pools'
    | '/_authenticated/staking/positions'
    | '/_authenticated/transactions/approvals'
    | '/_authenticated/transactions/batches'
    | '/_authenticated/wallets/analytics'
    | '/_authenticated/analytics/'
    | '/_authenticated/audit-logs/'
    | '/_authenticated/blockchain/'
    | '/_authenticated/governance/'
    | '/_authenticated/help-center/'
    | '/_authenticated/organizations/'
    | '/_authenticated/reports/'
    | '/_authenticated/security/'
    | '/_authenticated/settings/'
    | '/_authenticated/staking/'
    | '/_authenticated/transactions/'
    | '/_authenticated/users/'
    | '/_authenticated/wallets/'
    | '/_authenticated/governance/delegations/$id'
    | '/_authenticated/governance/proposals/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallets/': {
      id: '/_authenticated/wallets/'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof AuthenticatedWalletsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions/': {
      id: '/_authenticated/transactions/'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staking/': {
      id: '/_authenticated/staking/'
      path: '/staking'
      fullPath: '/staking'
      preLoaderRoute: typeof AuthenticatedStakingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/security/': {
      id: '/_authenticated/security/'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthenticatedSecurityIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organizations/': {
      id: '/_authenticated/organizations/'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof AuthenticatedOrganizationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/governance/': {
      id: '/_authenticated/governance/'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof AuthenticatedGovernanceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/blockchain/': {
      id: '/_authenticated/blockchain/'
      path: '/blockchain'
      fullPath: '/blockchain'
      preLoaderRoute: typeof AuthenticatedBlockchainIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit-logs/': {
      id: '/_authenticated/audit-logs/'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuthenticatedAuditLogsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics/': {
      id: '/_authenticated/analytics/'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallets/analytics': {
      id: '/_authenticated/wallets/analytics'
      path: '/wallets/analytics'
      fullPath: '/wallets/analytics'
      preLoaderRoute: typeof AuthenticatedWalletsAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions/batches': {
      id: '/_authenticated/transactions/batches'
      path: '/transactions/batches'
      fullPath: '/transactions/batches'
      preLoaderRoute: typeof AuthenticatedTransactionsBatchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions/approvals': {
      id: '/_authenticated/transactions/approvals'
      path: '/transactions/approvals'
      fullPath: '/transactions/approvals'
      preLoaderRoute: typeof AuthenticatedTransactionsApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staking/positions': {
      id: '/_authenticated/staking/positions'
      path: '/staking/positions'
      fullPath: '/staking/positions'
      preLoaderRoute: typeof AuthenticatedStakingPositionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staking/pools': {
      id: '/_authenticated/staking/pools'
      path: '/staking/pools'
      fullPath: '/staking/pools'
      preLoaderRoute: typeof AuthenticatedStakingPoolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/security/sessions': {
      id: '/_authenticated/security/sessions'
      path: '/security/sessions'
      fullPath: '/security/sessions'
      preLoaderRoute: typeof AuthenticatedSecuritySessionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/security/policies': {
      id: '/_authenticated/security/policies'
      path: '/security/policies'
      fullPath: '/security/policies'
      preLoaderRoute: typeof AuthenticatedSecurityPoliciesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/security/mpc-keys': {
      id: '/_authenticated/security/mpc-keys'
      path: '/security/mpc-keys'
      fullPath: '/security/mpc-keys'
      preLoaderRoute: typeof AuthenticatedSecurityMpcKeysRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/governance/proposals': {
      id: '/_authenticated/governance/proposals'
      path: '/governance/proposals'
      fullPath: '/governance/proposals'
      preLoaderRoute: typeof AuthenticatedGovernanceProposalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/governance/delegations': {
      id: '/_authenticated/governance/delegations'
      path: '/governance/delegations'
      fullPath: '/governance/delegations'
      preLoaderRoute: typeof AuthenticatedGovernanceDelegationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/blockchain/withdrawals': {
      id: '/_authenticated/blockchain/withdrawals'
      path: '/blockchain/withdrawals'
      fullPath: '/blockchain/withdrawals'
      preLoaderRoute: typeof AuthenticatedBlockchainWithdrawalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/blockchain/deposits': {
      id: '/_authenticated/blockchain/deposits'
      path: '/blockchain/deposits'
      fullPath: '/blockchain/deposits'
      preLoaderRoute: typeof AuthenticatedBlockchainDepositsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics/users': {
      id: '/_authenticated/analytics/users'
      path: '/analytics/users'
      fullPath: '/analytics/users'
      preLoaderRoute: typeof AuthenticatedAnalyticsUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics/risk': {
      id: '/_authenticated/analytics/risk'
      path: '/analytics/risk'
      fullPath: '/analytics/risk'
      preLoaderRoute: typeof AuthenticatedAnalyticsRiskRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics/real-time': {
      id: '/_authenticated/analytics/real-time'
      path: '/analytics/real-time'
      fullPath: '/analytics/real-time'
      preLoaderRoute: typeof AuthenticatedAnalyticsRealTimeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics/performance': {
      id: '/_authenticated/analytics/performance'
      path: '/analytics/performance'
      fullPath: '/analytics/performance'
      preLoaderRoute: typeof AuthenticatedAnalyticsPerformanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics/financial': {
      id: '/_authenticated/analytics/financial'
      path: '/analytics/financial'
      fullPath: '/analytics/financial'
      preLoaderRoute: typeof AuthenticatedAnalyticsFinancialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/governance/proposals/$id': {
      id: '/_authenticated/governance/proposals/$id'
      path: '/$id'
      fullPath: '/governance/proposals/$id'
      preLoaderRoute: typeof AuthenticatedGovernanceProposalsIdRouteImport
      parentRoute: typeof AuthenticatedGovernanceProposalsRoute
    }
    '/_authenticated/governance/delegations/$id': {
      id: '/_authenticated/governance/delegations/$id'
      path: '/$id'
      fullPath: '/governance/delegations/$id'
      preLoaderRoute: typeof AuthenticatedGovernanceDelegationsIdRouteImport
      parentRoute: typeof AuthenticatedGovernanceDelegationsRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedGovernanceDelegationsRouteChildren {
  AuthenticatedGovernanceDelegationsIdRoute: typeof AuthenticatedGovernanceDelegationsIdRoute
}

const AuthenticatedGovernanceDelegationsRouteChildren: AuthenticatedGovernanceDelegationsRouteChildren =
  {
    AuthenticatedGovernanceDelegationsIdRoute:
      AuthenticatedGovernanceDelegationsIdRoute,
  }

const AuthenticatedGovernanceDelegationsRouteWithChildren =
  AuthenticatedGovernanceDelegationsRoute._addFileChildren(
    AuthenticatedGovernanceDelegationsRouteChildren,
  )

interface AuthenticatedGovernanceProposalsRouteChildren {
  AuthenticatedGovernanceProposalsIdRoute: typeof AuthenticatedGovernanceProposalsIdRoute
}

const AuthenticatedGovernanceProposalsRouteChildren: AuthenticatedGovernanceProposalsRouteChildren =
  {
    AuthenticatedGovernanceProposalsIdRoute:
      AuthenticatedGovernanceProposalsIdRoute,
  }

const AuthenticatedGovernanceProposalsRouteWithChildren =
  AuthenticatedGovernanceProposalsRoute._addFileChildren(
    AuthenticatedGovernanceProposalsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAnalyticsFinancialRoute: typeof AuthenticatedAnalyticsFinancialRoute
  AuthenticatedAnalyticsPerformanceRoute: typeof AuthenticatedAnalyticsPerformanceRoute
  AuthenticatedAnalyticsRealTimeRoute: typeof AuthenticatedAnalyticsRealTimeRoute
  AuthenticatedAnalyticsRiskRoute: typeof AuthenticatedAnalyticsRiskRoute
  AuthenticatedAnalyticsUsersRoute: typeof AuthenticatedAnalyticsUsersRoute
  AuthenticatedBlockchainDepositsRoute: typeof AuthenticatedBlockchainDepositsRoute
  AuthenticatedBlockchainWithdrawalsRoute: typeof AuthenticatedBlockchainWithdrawalsRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedGovernanceDelegationsRoute: typeof AuthenticatedGovernanceDelegationsRouteWithChildren
  AuthenticatedGovernanceProposalsRoute: typeof AuthenticatedGovernanceProposalsRouteWithChildren
  AuthenticatedSecurityMpcKeysRoute: typeof AuthenticatedSecurityMpcKeysRoute
  AuthenticatedSecurityPoliciesRoute: typeof AuthenticatedSecurityPoliciesRoute
  AuthenticatedSecuritySessionsRoute: typeof AuthenticatedSecuritySessionsRoute
  AuthenticatedStakingPoolsRoute: typeof AuthenticatedStakingPoolsRoute
  AuthenticatedStakingPositionsRoute: typeof AuthenticatedStakingPositionsRoute
  AuthenticatedTransactionsApprovalsRoute: typeof AuthenticatedTransactionsApprovalsRoute
  AuthenticatedTransactionsBatchesRoute: typeof AuthenticatedTransactionsBatchesRoute
  AuthenticatedWalletsAnalyticsRoute: typeof AuthenticatedWalletsAnalyticsRoute
  AuthenticatedAnalyticsIndexRoute: typeof AuthenticatedAnalyticsIndexRoute
  AuthenticatedAuditLogsIndexRoute: typeof AuthenticatedAuditLogsIndexRoute
  AuthenticatedBlockchainIndexRoute: typeof AuthenticatedBlockchainIndexRoute
  AuthenticatedGovernanceIndexRoute: typeof AuthenticatedGovernanceIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedOrganizationsIndexRoute: typeof AuthenticatedOrganizationsIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedSecurityIndexRoute: typeof AuthenticatedSecurityIndexRoute
  AuthenticatedStakingIndexRoute: typeof AuthenticatedStakingIndexRoute
  AuthenticatedTransactionsIndexRoute: typeof AuthenticatedTransactionsIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedWalletsIndexRoute: typeof AuthenticatedWalletsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAnalyticsFinancialRoute: AuthenticatedAnalyticsFinancialRoute,
  AuthenticatedAnalyticsPerformanceRoute:
    AuthenticatedAnalyticsPerformanceRoute,
  AuthenticatedAnalyticsRealTimeRoute: AuthenticatedAnalyticsRealTimeRoute,
  AuthenticatedAnalyticsRiskRoute: AuthenticatedAnalyticsRiskRoute,
  AuthenticatedAnalyticsUsersRoute: AuthenticatedAnalyticsUsersRoute,
  AuthenticatedBlockchainDepositsRoute: AuthenticatedBlockchainDepositsRoute,
  AuthenticatedBlockchainWithdrawalsRoute:
    AuthenticatedBlockchainWithdrawalsRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedGovernanceDelegationsRoute:
    AuthenticatedGovernanceDelegationsRouteWithChildren,
  AuthenticatedGovernanceProposalsRoute:
    AuthenticatedGovernanceProposalsRouteWithChildren,
  AuthenticatedSecurityMpcKeysRoute: AuthenticatedSecurityMpcKeysRoute,
  AuthenticatedSecurityPoliciesRoute: AuthenticatedSecurityPoliciesRoute,
  AuthenticatedSecuritySessionsRoute: AuthenticatedSecuritySessionsRoute,
  AuthenticatedStakingPoolsRoute: AuthenticatedStakingPoolsRoute,
  AuthenticatedStakingPositionsRoute: AuthenticatedStakingPositionsRoute,
  AuthenticatedTransactionsApprovalsRoute:
    AuthenticatedTransactionsApprovalsRoute,
  AuthenticatedTransactionsBatchesRoute: AuthenticatedTransactionsBatchesRoute,
  AuthenticatedWalletsAnalyticsRoute: AuthenticatedWalletsAnalyticsRoute,
  AuthenticatedAnalyticsIndexRoute: AuthenticatedAnalyticsIndexRoute,
  AuthenticatedAuditLogsIndexRoute: AuthenticatedAuditLogsIndexRoute,
  AuthenticatedBlockchainIndexRoute: AuthenticatedBlockchainIndexRoute,
  AuthenticatedGovernanceIndexRoute: AuthenticatedGovernanceIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedOrganizationsIndexRoute: AuthenticatedOrganizationsIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedSecurityIndexRoute: AuthenticatedSecurityIndexRoute,
  AuthenticatedStakingIndexRoute: AuthenticatedStakingIndexRoute,
  AuthenticatedTransactionsIndexRoute: AuthenticatedTransactionsIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedWalletsIndexRoute: AuthenticatedWalletsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
